export {
    BASE_HOST,
    BASE_API_TIMEOUT,
    FORM_API_URL,
    ADMIN_API_PREFIX,
    REGISTRATION_API_PREFIX,
    APPLY_API_PREFIX,
    CODE_API_PREFIX,
    DENY_API_PREFIX,
    SIGN_API_PREFIX,
} from './common'
